### ISSUE TITLE
[WinError 193]% 1 is not a Win32 application

### ISSUE THREAD

**Issue by jonkryl** [ClaudiuGeorgiu/Obfuscapk#100]
Can't solve the problem

`C:\Obfuscapk\src>python -m obfuscapk.cli -o RandomManifest -o ClassRename -o ResStringEncryption -o AssetEncryption -o Goto -o FieldRename -o MethodRename -o ConstStringEncryption -o MethodOverload -o ArithmeticBranch -o Reorder -o Rebuild -o NewSignature -o NewAlignment -d C:\out\app-release.apk --ignore-libs -p --keystore-file C:\smsv2\debug.keystore --keystore-password android --key-alias moneydicealias --key-password android C:\release\app-release.apk
Running obfuscators (RandomManifest):   0%|                                                   |[00:00<?, ?obfuscator/s]07/06/2021 17:58:44> [ERROR][obfuscapk.tool.Apktool][decode()] Error during decoding: [WinError 193] %1 не является приложением Win32
07/06/2021 17:58:44> [ERROR][obfuscapk.obfuscation][decode_apk()] Error during apk decoding: [WinError 193] %1 не является приложением Win32
07/06/2021 17:58:44> [ERROR][yapsy_loaded_plugin_RandomManifest_1.random_manifest.RandomManifest][obfuscate()] Error during execution of "RandomManifest" obfuscator: [WinError 193] %1 не является приложением Win32
07/06/2021 17:58:44> [CRITICAL][obfuscapk.main][perform_obfuscation()] Error during obfuscation: [WinError 193] %1 не является приложением Win32
Traceback (most recent call last):
  File "C:\Obfuscapk\src\obfuscapk\main.py", line 151, in perform_obfuscation
    (obfuscator_name_to_function[obfuscator_name])(obfuscation)
  File "C:\Obfuscapk\src\obfuscapk\obfuscators\random_manifest\random_manifest.py", line 111, in obfuscate
    obfuscation_info.get_manifest_file(), parser=xml_parser
  File "C:\Obfuscapk\src\obfuscapk\obfuscation.py", line 578, in get_manifest_file
    self.decode_apk()
  File "C:\Obfuscapk\src\obfuscapk\obfuscation.py", line 341, in decode_apk
    apktool.decode(self.apk_path, self._decoded_apk_path, force=True)
  File "C:\Obfuscapk\src\obfuscapk\tool.py", line 104, in decode
    output = subprocess.check_output(
  File "C:\Program Files\Python39\lib\subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "C:\Program Files\Python39\lib\subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Program Files\Python39\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Program Files\Python39\lib\subprocess.py", line 1420, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
OSError: [WinError 193] %1 не является приложением Win32
Running obfuscators (RandomManifest):   0%|                                                   |[00:00<?, ?obfuscator/s]
Traceback (most recent call last):
  File "C:\Program Files\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Obfuscapk\src\obfuscapk\cli.py", line 188, in <module>
    main()
  File "C:\Obfuscapk\src\obfuscapk\cli.py", line 170, in main
    perform_obfuscation(
  File "C:\Obfuscapk\src\obfuscapk\main.py", line 151, in perform_obfuscation
    (obfuscator_name_to_function[obfuscator_name])(obfuscation)
  File "C:\Obfuscapk\src\obfuscapk\obfuscators\random_manifest\random_manifest.py", line 111, in obfuscate
    obfuscation_info.get_manifest_file(), parser=xml_parser
  File "C:\Obfuscapk\src\obfuscapk\obfuscation.py", line 578, in get_manifest_file
    self.decode_apk()
  File "C:\Obfuscapk\src\obfuscapk\obfuscation.py", line 341, in decode_apk
    apktool.decode(self.apk_path, self._decoded_apk_path, force=True)
  File "C:\Obfuscapk\src\obfuscapk\tool.py", line 104, in decode
    output = subprocess.check_output(
  File "C:\Program Files\Python39\lib\subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "C:\Program Files\Python39\lib\subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Program Files\Python39\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Program Files\Python39\lib\subprocess.py", line 1420, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
OSError: [WinError 193] %1 не является приложением Win32`

**Comment by jonkryl** [comment]
https://github.com/ClaudiuGeorgiu/Obfuscapk/issues/75

**Comment by jonkryl** [comment]
![изображение](https://user-images.githubusercontent.com/13360676/121006569-395add00-c7bb-11eb-8a96-2aed3a1d8093.png)
