### ISSUE TITLE
error executing obfuscated command in windows 10

### ISSUE THREAD

**Issue by ImanCol** [ClaudiuGeorgiu/Obfuscapk#11]
executed this command  ``python -m obfuscapk.cli -o RandomManifest 1.apk``

I returned this error:

> 26/02/2020 15:20:35> [ERROR][obfuscapk.tool.Apktool][decode()] Error during decoding: [WinError 2] El sistema no puede encontrar el archivo especificado
26/02/2020 15:20:35> [ERROR][obfuscapk.obfuscation][decode_apk()] Error during apk decoding: [WinError 2] El sistema no puede encontrar el archivo especificado
26/02/2020 15:20:35> [ERROR][yapsy_loaded_plugin_RandomManifest_1.random_manifest.RandomManifest][obfuscate()] Error during execution of "RandomManifest" obfuscator: [WinError 2] El sistema no puede encontrar el archivo especificado
26/02/2020 15:20:35> [CRITICAL][obfuscapk.main][perform_obfuscation()] Error during obfuscation: [WinError 2] El sistema no puede encontrar el archivo especificado
Traceback (most recent call last):
  File "E:\Android\Github\Obfuscade\Obfuscapk\src\obfuscapk\main.py", line 88, in perform_obfuscation
    (obfuscator_name_to_function[obfuscator_name])(obfuscation)
  File "E:\Android\Github\Obfuscade\Obfuscapk\src\obfuscapk\obfuscators\random_manifest\random_manifest.py", line 108, in obfuscate
    manifest_tree = Xml.parse(obfuscation_info.get_manifest_file(), parser=xml_parser)
  File "E:\Android\Github\Obfuscade\Obfuscapk\src\obfuscapk\obfuscation.py", line 439, in get_manifest_file
    self.decode_apk()
  File "E:\Android\Github\Obfuscade\Obfuscapk\src\obfuscapk\obfuscation.py", line 276, in decode_apk
    apktool.decode(self.apk_path, self._decoded_apk_path, force=True)
  File "E:\Android\Github\Obfuscade\Obfuscapk\src\obfuscapk\tool.py", line 61, in decode
    output = subprocess.check_output(decode_cmd, stderr=subprocess.STDOUT).strip()
  File "C:\Python37\lib\subprocess.py", line 376, in check_output
    **kwargs).stdout
  File "C:\Python37\lib\subprocess.py", line 453, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Python37\lib\subprocess.py", line 756, in __init__
    restore_signals, start_new_session)
  File "C:\Python37\lib\subprocess.py", line 1155, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] El sistema no puede encontrar el archivo especificado
Traceback (most recent call last):
  File "C:\Python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "E:\Android\Github\Obfuscade\Obfuscapk\src\obfuscapk\cli.py", line 81, in <module>
    arguments.interactive, arguments.ignore_libs, arguments.virus_total_key)
  File "E:\Android\Github\Obfuscade\Obfuscapk\src\obfuscapk\main.py", line 88, in perform_obfuscation
    (obfuscator_name_to_function[obfuscator_name])(obfuscation)
  File "E:\Android\Github\Obfuscade\Obfuscapk\src\obfuscapk\obfuscators\random_manifest\random_manifest.py", line 108, in obfuscate
    manifest_tree = Xml.parse(obfuscation_info.get_manifest_file(), parser=xml_parser)
  File "E:\Android\Github\Obfuscade\Obfuscapk\src\obfuscapk\obfuscation.py", line 439, in get_manifest_file
    self.decode_apk()
  File "E:\Android\Github\Obfuscade\Obfuscapk\src\obfuscapk\obfuscation.py", line 276, in decode_apk
    apktool.decode(self.apk_path, self._decoded_apk_path, force=True)
  File "E:\Android\Github\Obfuscade\Obfuscapk\src\obfuscapk\tool.py", line 61, in decode
    output = subprocess.check_output(decode_cmd, stderr=subprocess.STDOUT).strip()
  File "C:\Python37\lib\subprocess.py", line 376, in check_output
    **kwargs).stdout
  File "C:\Python37\lib\subprocess.py", line 453, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Python37\lib\subprocess.py", line 756, in __init__
    restore_signals, start_new_session)
  File "C:\Python37\lib\subprocess.py", line 1155, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] El sistema no puede encontrar el archivo especificado

> 

Windows 10, 64 Bit.

**Comment by ImanCol** [comment]
place the apktool.jar, apktool.bat, jarsigner, zipalign files in the same Obfuscapk \ src directory and I get these errors

> E:\Android\Github\Obfuscade\Obfuscapk\src>python -m obfuscapk.cli -o Nop -o RandomManifest -o Rebuild -o NewSignature -o NewAlignment -p 1.apk
Running obfuscators (Nop):   0%|                                                              |[00:00<?, ?obfuscator/s]26/02/2020 16:39:26> [ERROR][obfuscapk.tool.Apktool][decode()] Error during decoding: [WinError 2] El sistema no puede encontrar el archivo especificado
26/02/2020 16:39:26> [ERROR][obfuscapk.obfuscation][decode_apk()] Error during apk decoding: [WinError 2] El sistema no puede encontrar el archivo especificado
26/02/2020 16:39:26> [ERROR][yapsy_loaded_plugin_Nop_1.nop.Nop][obfuscate()] Error during execution of "Nop" obfuscator: [WinError 2] El sistema no puede encontrar el archivo especificado
26/02/2020 16:39:26> [CRITICAL][obfuscapk.main][perform_obfuscation()] Error during obfuscation: [WinError 2] El sistema no puede encontrar el archivo especificado
Traceback (most recent call last):
  File "E:\Android\Github\Obfuscade\Obfuscapk\src\obfuscapk\main.py", line 88, in perform_obfuscation
    (obfuscator_name_to_function[obfuscator_name])(obfuscation)
  File "E:\Android\Github\Obfuscade\Obfuscapk\src\obfuscapk\obfuscators\nop\nop.py", line 25, in obfuscate
    for smali_file in util.show_list_progress(obfuscation_info.get_smali_files(),
  File "E:\Android\Github\Obfuscade\Obfuscapk\src\obfuscapk\obfuscation.py", line 446, in get_smali_files
    self.decode_apk()
  File "E:\Android\Github\Obfuscade\Obfuscapk\src\obfuscapk\obfuscation.py", line 276, in decode_apk
    apktool.decode(self.apk_path, self._decoded_apk_path, force=True)
  File "E:\Android\Github\Obfuscade\Obfuscapk\src\obfuscapk\tool.py", line 61, in decode
    output = subprocess.check_output(decode_cmd, stderr=subprocess.STDOUT).strip()
  File "C:\Python37\lib\subprocess.py", line 376, in check_output
    **kwargs).stdout
  File "C:\Python37\lib\subprocess.py", line 453, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Python37\lib\subprocess.py", line 756, in __init__
    restore_signals, start_new_session)
  File "C:\Python37\lib\subprocess.py", line 1155, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] El sistema no puede encontrar el archivo especificado
Traceback (most recent call last):
  File "C:\Python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "E:\Android\Github\Obfuscade\Obfuscapk\src\obfuscapk\cli.py", line 81, in <module>
    arguments.interactive, arguments.ignore_libs, arguments.virus_total_key)
  File "E:\Android\Github\Obfuscade\Obfuscapk\src\obfuscapk\main.py", line 88, in perform_obfuscation
    (obfuscator_name_to_function[obfuscator_name])(obfuscation)
  File "E:\Android\Github\Obfuscade\Obfuscapk\src\obfuscapk\obfuscators\nop\nop.py", line 25, in obfuscate
    for smali_file in util.show_list_progress(obfuscation_info.get_smali_files(),
  File "E:\Android\Github\Obfuscade\Obfuscapk\src\obfuscapk\obfuscation.py", line 446, in get_smali_files
    self.decode_apk()
  File "E:\Android\Github\Obfuscade\Obfuscapk\src\obfuscapk\obfuscation.py", line 276, in decode_apk
    apktool.decode(self.apk_path, self._decoded_apk_path, force=True)
  File "E:\Android\Github\Obfuscade\Obfuscapk\src\obfuscapk\tool.py", line 61, in decode
    output = subprocess.check_output(decode_cmd, stderr=subprocess.STDOUT).strip()
  File "C:\Python37\lib\subprocess.py", line 376, in check_output
    **kwargs).stdout
  File "C:\Python37\lib\subprocess.py", line 453, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Python37\lib\subprocess.py", line 756, in __init__
    restore_signals, start_new_session)
  File "C:\Python37\lib\subprocess.py", line 1155, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] El sistema no puede encontrar el archivo especificado
Running obfuscators (Nop):   0%|                                                              |[00:00<?, ?obfuscator/s]

E:\Android\Github\Obfuscade\Obfuscapk\src>

**Comment by ClaudiuGeorgiu** [comment]
Hi, please try specifying the location of the executables through the following environment variables: `APKTOOL_PATH`, `JARSIGNER_PATH` and `ZIPALIGN_PATH`. If this still doesn't work, you can try this solution: https://github.com/ClaudiuGeorgiu/Obfuscapk/issues/7#issuecomment-589559042

**Comment by ClaudiuGeorgiu** [comment]
This error should be solved with latest commit 97cb05e19fa6b5635f96083b48639de157115217.
