### ISSUE TITLE
No module named 'tqdm' on Ubuntu 18.04

### ISSUE THREAD

**Issue by mightybulacs** [ClaudiuGeorgiu/Obfuscapk#13]
Hello,
I am trying to install this on my machine following the instructions provided on this repository. All installation from src/requirements.txt succeed

But when trying to execute python3.7 -m obfuscapk.cli --help, it threw the error below

secret@secret:~/penetration_testing/android/Obfuscapk/src$ python3.7 -m obfuscapk.cli --help
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/secret/penetration_testing/android/Obfuscapk/src/obfuscapk/cli.py", line 7, in <module>
    from .main import perform_obfuscation, check_external_tool_dependencies
  File "/home/secret/penetration_testing/android/Obfuscapk/src/obfuscapk/main.py", line 9, in <module>
    from . import util
  File "/home/secret/penetration_testing/android/Obfuscapk/src/obfuscapk/util.py", line 14, in <module>
    from tqdm import tqdm
ModuleNotFoundError: No module named 'tqdm'

**Comment by mightybulacs** [comment]
In addition, environment variables are also set properly

**Comment by mightybulacs** [comment]
Apologies, I managed to fix it my bad
