### ISSUE TITLE
Installation failure - dependancy check

### ISSUE THREAD

**Issue by knightrider-kit** [ClaudiuGeorgiu/Obfuscapk#130]
### Prerequisites

Before opening this issue, I tried the following steps:

* [ ] Installed the tool in a way [described in the readme](https://github.com/ClaudiuGeorgiu/Obfuscapk#-installation) and ran `python3 -m obfuscapk.cli --help` without any errors

* [ ] Ran the tool using: `python3 -m obfuscapk.cli -o Rebuild -o NewAlignment -o NewSignature <YOUR_APP.APK>` to verify that the app is not using anti-repackaging techniques

* [x] Ran the tool using `--ignore-libs` flag to exclude third party libraries from the obfuscation

* [x] Checked [FAQ](https://github.com/ClaudiuGeorgiu/Obfuscapk/blob/master/docs/FAQ.md) and [troubleshooting](https://github.com/ClaudiuGeorgiu/Obfuscapk/blob/master/docs/TROUBLESHOOTING.md)

* [x] Checked for [existing similar issues on GitHub](https://github.com/issues?utf8=✓&q=is%3Aissue+repo%3AClaudiuGeorgiu/Obfuscapk)

### Description

Installed the tool in a way [described in the readme](https://github.com/ClaudiuGeorgiu/Obfuscapk#-installation) and ran `python3 -m obfuscapk.cli --help`
But got an error referencing bundledecompiler.
Did not think I was required to have bundledecompiler.

### Steps to reproduce

1. 
2. 
3. 
Install following readme

**Expected behavior:**

Help dialog appears.

**Actual behavior:**

Received error.
```
paste here the complete error message, including the command that generated the error
0:/usr/src/Obfuscapk/src#>python3 -m obfuscapk.cli --help
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/src/Obfuscapk/src/obfuscapk/cli.py", line 189, in <module>
    main()
  File "/usr/src/Obfuscapk/src/obfuscapk/cli.py", line 140, in main
    check_external_tool_dependencies()
  File "/usr/src/Obfuscapk/src/obfuscapk/main.py", line 42, in check_external_tool_dependencies
    BundleDecompiler()
  File "/usr/src/Obfuscapk/src/obfuscapk/toolbundledecompiler.py", line 31, in __init__
    if not os.path.isfile(full_bundledecompiler_path):
  File "/usr/local/lib/python3.7/genericpath.py", line 30, in isfile
    st = os.stat(path)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType
```

### Versions

* **Installation mode** (e.g., from source or with Docker):source
* **Obufscapk version** (e.g., commit 0676488):not sure wherebto find that but cloned on 3-11
* **OS** (e.g., Ubuntu 16.04):Ubuntu 14.04
* **Python version** (e.g., 3.7.4):3.7.4
* **Apktool version** (e.g., v2.4.0):2.6.1

### Additional information

**Apk file(s):**

**Comment by knightrider-kit** [comment]
Installing BundleDecompiler-0.0.2.jar has fixed the issue but I had no plan to use it.
