### ISSUE TITLE
Problems with BundleDecompiler.jar

### ISSUE THREAD

**Issue by timwu118841** [ClaudiuGeorgiu/Obfuscapk#139]
shutil.which()  cant find the path to BundleDecompiler.jar both on Mac os and Windows 
it return none Type and cause the Error  
but i already put it in /usr/local/bin
Traceback (most recent call last):
  File "/Users/tiwubd/.pyenv/versions/3.9.12/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/tiwubd/.pyenv/versions/3.9.12/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/tiwubd/Obfuscapk/src/obfuscapk/cli.py", line 189, in <module>
    main()
  File "/Users/tiwubd/Obfuscapk/src/obfuscapk/cli.py", line 140, in main
    check_external_tool_dependencies()
  File "/Users/tiwubd/Obfuscapk/src/obfuscapk/main.py", line 42, in check_external_tool_dependencies
    BundleDecompiler()
  File "/Users/tiwubd/Obfuscapk/src/obfuscapk/toolbundledecompiler.py", line 31, in __init__
    if not os.path.isfile(full_bundledecompiler_path):
  File "/Users/tiwubd/.pyenv/versions/3.9.12/lib/python3.9/genericpath.py", line 30, in isfile
    st = os.stat(path)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType

**Comment by ClaudiuGeorgiu** [comment]
Hi, please also make sure that `BundleDecompiler.jar` has the executable flag set (`chmod +x BundleDecompiler.jar`).

**Comment by knightrider-kit** [comment]
@timwu118841
Also check if your file name is still BundleDecompiler-0.0.2.jar and if so either rename or make link to BundleDecompiler.jar.

**Comment by Crypton1337** [comment]
@knightrider-kit I have installed BundleDecompiler.jar but I don't know where to put it and the device I'm using is kali linux please help me

**Comment by ClaudiuGeorgiu** [comment]
Hi @Crypton1337, as described in the readme, you can put BundleDecompiler.jar in any directory included in `PATH`, usually `/usr/local/bin` or `/usr/bin` should work.
