### ISSUE TITLE
The Obfuscation process halted on 43%

### ISSUE THREAD

**Issue by mightybulacs** [ClaudiuGeorgiu/Obfuscapk#14]
Encrypting constant strings: 100%|█████████████████████████████████████████████████████████████████████████████████████|[00:09<00:00, 772.12file/s]
Inserting "nop" instructions in smali files: 100%|████████████████████████████████████████████████████████████████████|[00:06<00:00, 1224.65file/s]
Inserting "goto" instructions in smali files: 100%|███████████████████████████████████████████████████████████████████|[00:06<00:00, 1258.33file/s]
Running obfuscators (Rebuild):  43%|█████████████████████████████████▍                                            |[00:30<00:47, 11.93s/obfuscator]27/03/2020 14:07:35> [ERROR][obfuscapk.tool.Apktool][build()] Error during build command: I: Using Apktool 2.4.1
I: Smaling smali folder into classes.dex...
I: Building resources...
W: invalid resource directory name: /home/secret/Desktop/testedapks/kaloka/res navigation
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/tmp/brut_util_Jar_8524507960092424740.tmp, p, --forced-package-id, 127, --min-sdk-version, 22, --target-sdk-version, 29, --version-code, 1, --version-name, 1.0.17, --no-version-vectors, -F, /tmp/APKTOOL991550281430554690.tmp, -e, /tmp/APKTOOL21718041769775050.tmp, -0, arsc, -I, /home/secret/.local/share/apktool/framework/1.apk, -S, /home/secret/Desktop/testedapks/kaloka/res, -M, /home/secret/Desktop/testedapks/kaloka/AndroidManifest.xml]

27/03/2020 14:07:35> [ERROR][obfuscapk.obfuscation][build_obfuscated_apk()] Error during apk building: Command '['apktool', 'b', '--force-all', '/home/secret/Desktop/testedapks/kaloka', '-o', '/home/secret/Desktop/kaloka.apk']' returned non-zero exit status 1.
27/03/2020 14:07:35> [ERROR][yapsy_loaded_plugin_Rebuild_1.rebuild.Rebuild][obfuscate()] Error during execution of "Rebuild" obfuscator: Command '['apktool', 'b', '--force-all', '/home/secret/Desktop/testedapks/kaloka', '-o', '/home/secret/Desktop/kaloka.apk']' returned non-zero exit status 1.
27/03/2020 14:07:35> [CRITICAL][obfuscapk.main][perform_obfuscation()] Error during obfuscation: Command '['apktool', 'b', '--force-all', '/home/secret/Desktop/testedapks/kaloka', '-o', '/home/secret/Desktop/kaloka.apk']' returned non-zero exit status 1.
Traceback (most recent call last):
  File "/home/secret/penetration_testing/android/Obfuscapk/src/obfuscapk/main.py", line 88, in perform_obfuscation
    (obfuscator_name_to_function[obfuscator_name])(obfuscation)
  File "/home/secret/penetration_testing/android/Obfuscapk/src/obfuscapk/obfuscators/rebuild/rebuild.py", line 20, in obfuscate
    obfuscation_info.build_obfuscated_apk()
  File "/home/secret/penetration_testing/android/Obfuscapk/src/obfuscapk/obfuscation.py", line 396, in build_obfuscated_apk
    apktool.build(self._decoded_apk_path, self.obfuscated_apk_path)
  File "/home/secret/penetration_testing/android/Obfuscapk/src/obfuscapk/tool.py", line 93, in build
    output = subprocess.check_output(build_cmd, stderr=subprocess.STDOUT).strip()
  File "/usr/lib/python3.7/subprocess.py", line 411, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['apktool', 'b', '--force-all', '/home/secret/Desktop/testedapks/kaloka', '-o', '/home/secret/Desktop/kaloka.apk']' returned non-zero exit status 1.
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/secret/penetration_testing/android/Obfuscapk/src/obfuscapk/cli.py", line 81, in <module>
    arguments.interactive, arguments.ignore_libs, arguments.virus_total_key)
  File "/home/secret/penetration_testing/android/Obfuscapk/src/obfuscapk/main.py", line 88, in perform_obfuscation
    (obfuscator_name_to_function[obfuscator_name])(obfuscation)
  File "/home/secret/penetration_testing/android/Obfuscapk/src/obfuscapk/obfuscators/rebuild/rebuild.py", line 20, in obfuscate
    obfuscation_info.build_obfuscated_apk()
  File "/home/secret/penetration_testing/android/Obfuscapk/src/obfuscapk/obfuscation.py", line 396, in build_obfuscated_apk
    apktool.build(self._decoded_apk_path, self.obfuscated_apk_path)
  File "/home/secret/penetration_testing/android/Obfuscapk/src/obfuscapk/tool.py", line 93, in build
    output = subprocess.check_output(build_cmd, stderr=subprocess.STDOUT).strip()
  File "/usr/lib/python3.7/subprocess.py", line 411, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['apktool', 'b', '--force-all', '/home/secret/Desktop/testedapks/kaloka', '-o', '/home/secret/Desktop/kaloka.apk']' returned non-zero exit status 1.
Running obfuscators (Rebuild):  43%|█████████████████████████████████▍                                            |[00:45<01:00, 15.04s/obfuscator]

**Comment by ClaudiuGeorgiu** [comment]
Hi, please format your issue by following the [bug report issue template](https://github.com/ClaudiuGeorgiu/Obfuscapk/blob/3adbf7bfa84adf117326409c683e375ceb5a5df4/.github/ISSUE_TEMPLATE/bug_report.md).
