### ISSUE TITLE
Error during apk decoding

### ISSUE THREAD

**Issue by punhat** [ClaudiuGeorgiu/Obfuscapk#15]
- [x] Installed the tool in a way [described in the readme](https://github.com/ClaudiuGeorgiu/Obfuscapk#-installation) and ran `python3 -m obfuscapk.cli --help` without any errors
- [x] Ran the tool using only `Rebuild`, `NewSignature` and `NewAlignment` obfuscators to verify that the app is not using anti-repackaging techniques
- [x] Ran the tool using `--ignore-libs` to exclude third party libraries from the obfuscation
- [x] Checked that the issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+repo%3AClaudiuGeorgiu/Obfuscapk>

### Steps to Reproduce

1. git clone https://github.com/ClaudiuGeorgiu/Obfuscapk.git
2. python3.7 -m pip install -r src/requirements.txt
3. cd src/
4. python3.7 -m obfuscapk.cli --help (shows help as expected)
5. obfuscapk -o RandomManifest -o Rebuild -o NewSignature -o NewAlignment original.apk

**Expected behavior:**

The obsfuscation should decompile and obfuscate code and then it should compile and sign the apk

**Actual behavior:**

After running the command it starts to decompile apk and then throws an error, working directory is empty with just folder name

```
if applicable, paste here the complete error message

root@kali:~/Obfuscapk/src# python3.7 -m obfuscapk.cli -o Rebuild -o NewAlignment --ignore-libs  original.apk 
01/04/2020 15:17:24> [ERROR][obfuscapk.tool.Apktool][decode()] Error during decode command: I: Using Apktool 2.4.0 on original.apk
Exception in thread "main" brut.androlib.AndrolibException: brut.directory.DirectoryException: java.util.zip.ZipException: zip file is empty
	at brut.androlib.ApkDecoder.hasResources(ApkDecoder.java:307)
	at brut.androlib.ApkDecoder.decode(ApkDecoder.java:103)
	at brut.apktool.Main.cmdDecode(Main.java:167)
	at brut.apktool.Main.main(Main.java:76)
Caused by: brut.directory.DirectoryException: java.util.zip.ZipException: zip file is empty
	at brut.directory.ZipRODirectory.<init>(ZipRODirectory.java:55)
	at brut.directory.ZipRODirectory.<init>(ZipRODirectory.java:38)
	at brut.directory.ExtFile.getDirectory(ExtFile.java:52)
	at brut.androlib.ApkDecoder.hasResources(ApkDecoder.java:305)
	... 3 more
Caused by: java.util.zip.ZipException: zip file is empty
	at java.base/java.util.zip.ZipFile$Source.zerror(ZipFile.java:1529)
	at java.base/java.util.zip.ZipFile$Source.findEND(ZipFile.java:1343)
	at java.base/java.util.zip.ZipFile$Source.initCEN(ZipFile.java:1437)
	at java.base/java.util.zip.ZipFile$Source.<init>(ZipFile.java:1268)
	at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1231)
	at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:726)
	at java.base/java.util.zip.ZipFile$CleanableResource.get(ZipFile.java:843)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:246)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:176)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:190)
	at brut.directory.ZipRODirectory.<init>(ZipRODirectory.java:53)
	... 6 more

01/04/2020 15:17:24> [ERROR][obfuscapk.obfuscation][decode_apk()] Error during apk decoding: Command '['apktool', 'd', '--force', 'original.apk', '-o', 'obfuscation_working_dir/original']' returned non-zero exit status 1.
01/04/2020 15:17:24> [ERROR][yapsy_loaded_plugin_Rebuild_1.rebuild.Rebuild][obfuscate()] Error during execution of "Rebuild" obfuscator: Command '['apktool', 'd', '--force', 'original.apk', '-o', 'obfuscation_working_dir/original']' returned non-zero exit status 1.
01/04/2020 15:17:24> [CRITICAL][obfuscapk.main][perform_obfuscation()] Error during obfuscation: Command '['apktool', 'd', '--force', 'original.apk', '-o', 'obfuscation_working_dir/original']' returned non-zero exit status 1.
Traceback (most recent call last):
  File "/root/Obfuscapk/src/obfuscapk/main.py", line 88, in perform_obfuscation
    (obfuscator_name_to_function[obfuscator_name])(obfuscation)
  File "/root/Obfuscapk/src/obfuscapk/obfuscators/rebuild/rebuild.py", line 20, in obfuscate
    obfuscation_info.build_obfuscated_apk()
  File "/root/Obfuscapk/src/obfuscapk/obfuscation.py", line 390, in build_obfuscated_apk
    self.decode_apk()
  File "/root/Obfuscapk/src/obfuscapk/obfuscation.py", line 276, in decode_apk
    apktool.decode(self.apk_path, self._decoded_apk_path, force=True)
  File "/root/Obfuscapk/src/obfuscapk/tool.py", line 61, in decode
    output = subprocess.check_output(decode_cmd, stderr=subprocess.STDOUT).strip()
  File "/usr/lib/python3.7/subprocess.py", line 411, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['apktool', 'd', '--force', 'original.apk', '-o', 'obfuscation_working_dir/original']' returned non-zero exit status 1.
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/root/Obfuscapk/src/obfuscapk/cli.py", line 81, in <module>
    arguments.interactive, arguments.ignore_libs, arguments.virus_total_key)
  File "/root/Obfuscapk/src/obfuscapk/main.py", line 88, in perform_obfuscation
    (obfuscator_name_to_function[obfuscator_name])(obfuscation)
  File "/root/Obfuscapk/src/obfuscapk/obfuscators/rebuild/rebuild.py", line 20, in obfuscate
    obfuscation_info.build_obfuscated_apk()
  File "/root/Obfuscapk/src/obfuscapk/obfuscation.py", line 390, in build_obfuscated_apk
    self.decode_apk()
  File "/root/Obfuscapk/src/obfuscapk/obfuscation.py", line 276, in decode_apk
    apktool.decode(self.apk_path, self._decoded_apk_path, force=True)
  File "/root/Obfuscapk/src/obfuscapk/tool.py", line 61, in decode
    output = subprocess.check_output(decode_cmd, stderr=subprocess.STDOUT).strip()
  File "/usr/lib/python3.7/subprocess.py", line 411, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['apktool', 'd', '--force', 'original.apk', '-o', 'obfuscation_working_dir/original']' returned non-zero exit status 1.

```

### Versions

- **Installation mode** (from source code):
- **Obufscapk version** (commit 3adbf7b):
- **OS** (Kali linux 2019-1):
- **Python version** (Python 3.7.7):

### Additional Information

i also used apktool_fix_kali_2019 script to make sure its not apktool problem
i also tried to decompile the same apk directly with apktool d original.apk, it works as expected
i also tried with different apk, the problem persist
its a metasploit payload with local ip for testing in LAN

apk file 
[original.zip](https://github.com/ClaudiuGeorgiu/Obfuscapk/files/4414440/original.zip)

**Comment by ClaudiuGeorgiu** [comment]
Hi, can you please format the issue by following the [bug report issue template](https://github.com/ClaudiuGeorgiu/Obfuscapk/blob/3adbf7bfa84adf117326409c683e375ceb5a5df4/.github/ISSUE_TEMPLATE/bug_report.md)? What is the operating system? Can you provide the apk sample?

**Comment by punhat** [comment]
edited with bug report template

**Comment by ClaudiuGeorgiu** [comment]
Thanks for the update, I downloaded the `original.zip` archive and it contains a file named `original.apk` that is empty, this is the reason for the `java.util.zip.ZipException: zip file is empty` error.

**Comment by punhat** [comment]
i'm so sorry for doing such a silly. i made another metasploit payload and it worked as expected, Thanks. However my main goal was to obfuscate another apk and since i was getting error with that i tried it with metasploit payload and didn't notice such a silly mistake. could you please have a look to the given apk and check whats wrong with it, i am still not able to obfuscate test.apk

<h3> Steps to Reproduce</h3>
1) python3.7 -m obfuscapk.cli -o Rebuild -o NewSignature -o NewAlignment test.apk

It will surely throw an error, its a spynote payload with local IP.

[test.zip](https://github.com/ClaudiuGeorgiu/Obfuscapk/files/4416596/test.zip)

**Comment by ClaudiuGeorgiu** [comment]
I ran the following command on the new file you provided:
```
python3.7 -m obfuscapk.cli -o Rebuild -o NewSignature -o NewAlignment app-release_zipaligned.apk
```
In my case Obfuscapk finished without errors and successfully generated the obfuscated apk (I didn't try to run the new apk, so I don't know if it actually works on a device). I'm using the latest version of Obfuscapk on master branch, running on Ubuntu 16.

**Comment by punhat** [comment]
I've noticed there is a problem with my apktool while recompiling,  Thanks anyways, you've been very helpful, since it is not your tools problem I'll close the thread. 
Thanks.
