### ISSUE TITLE
path error

### ISSUE THREAD

**Issue by HoseinGhadiri** [ClaudiuGeorgiu/Obfuscapk#163]
i got this error : 

Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/hosein/Android/Obfuscapk/Obfuscapk/src/obfuscapk/cli.py", line 189, in <module>
    main()
  File "/home/hosein/Android/Obfuscapk/Obfuscapk/src/obfuscapk/cli.py", line 140, in main
    check_external_tool_dependencies()
  File "/home/hosein/Android/Obfuscapk/Obfuscapk/src/obfuscapk/main.py", line 42, in check_external_tool_dependencies
    BundleDecompiler()
  File "/home/hosein/Android/Obfuscapk/Obfuscapk/src/obfuscapk/toolbundledecompiler.py", line 31, in __init__
    if not os.path.isfile(full_bundledecompiler_path):
  File "/usr/lib/python3.10/genericpath.py", line 30, in isfile
    st = os.stat(path)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType

**Comment by ClaudiuGeorgiu** [comment]
Closing as duplicate of https://github.com/ClaudiuGeorgiu/Obfuscapk/issues/130.
