### ISSUE TITLE
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType

### ISSUE THREAD

**Issue by skjose0705** [ClaudiuGeorgiu/Obfuscapk#166]
When I execute, appears this error

python3 -m obfuscapk.cli --help
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/root/Obfuscapk/src/obfuscapk/cli.py", line 189, in <module>
    main()
  File "/root/Obfuscapk/src/obfuscapk/cli.py", line 140, in main
    check_external_tool_dependencies()
  File "/root/Obfuscapk/src/obfuscapk/main.py", line 42, in check_external_tool_dependencies
    BundleDecompiler()
  File "/root/Obfuscapk/src/obfuscapk/toolbundledecompiler.py", line 31, in __init__
    if not os.path.isfile(full_bundledecompiler_path):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen genericpath>", line 30, in isfile
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType

**Comment by ClaudiuGeorgiu** [comment]
Hi, please see https://github.com/ClaudiuGeorgiu/Obfuscapk/issues/130.
