### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by dfdfdfs** [ClaudiuGeorgiu/Obfuscapk#2]
Hi I have Unbynty 16.04 32 bit

 After the command **python3.7-m obfuscapk.cli --help** error 

```
ggg@ubuntu:~/Downloads/Obfuscapk-master$ cd src/
ggg@ubuntu:~/Downloads/Obfuscapk-master/src$ python3.7 -m obfuscapk.cli --help
07/09/2019 23:10:23> [ERROR][yapsy][loadPlugins()] Unable to import plugin: /home/ggg/Downloads/Obfuscapk-master/src/obfuscapk/obfuscators/res_string_encryption
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/yapsy/PluginManager.py", line 518, in loadPlugins
    candidate_module = PluginManager._importModule(plugin_module_name, candidate_filepath)
  File "/usr/local/lib/python3.7/dist-packages/yapsy/PluginManager.py", line 581, in _importModule
    candidate_module = imp.load_module(plugin_module_name,None,candidate_filepath,("py","r",imp.PKG_DIRECTORY))
  File "/usr/lib/python3.7/imp.py", line 244, in load_module
    return load_package(name, filename)
  File "/usr/lib/python3.7/imp.py", line 216, in load_package
    return _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ggg/Downloads/Obfuscapk-master/src/obfuscapk/obfuscators/res_string_encryption/__init__.py", line 4, in <module>
    from .res_string_encryption import ResStringEncryption
  File "/home/ggg/Downloads/Obfuscapk-master/src/obfuscapk/obfuscators/res_string_encryption/res_string_encryption.py", line 11, in <module>
    from Crypto.Cipher import AES
ModuleNotFoundError: No module named 'Crypto'
07/09/2019 23:10:23> [ERROR][yapsy][loadPlugins()] Unable to import plugin: /home/ggg/Downloads/Obfuscapk-master/src/obfuscapk/obfuscators/virus_total
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/yapsy/PluginManager.py", line 518, in loadPlugins
    candidate_module = PluginManager._importModule(plugin_module_name, candidate_filepath)
  File "/usr/local/lib/python3.7/dist-packages/yapsy/PluginManager.py", line 581, in _importModule
    candidate_module = imp.load_module(plugin_module_name,None,candidate_filepath,("py","r",imp.PKG_DIRECTORY))
  File "/usr/lib/python3.7/imp.py", line 244, in load_module
    return load_package(name, filename)
  File "/usr/lib/python3.7/imp.py", line 216, in load_package
    return _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ggg/Downloads/Obfuscapk-master/src/obfuscapk/obfuscators/virus_total/__init__.py", line 4, in <module>
    from .virus_total import VirusTotal
  File "/home/ggg/Downloads/Obfuscapk-master/src/obfuscapk/obfuscators/virus_total/virus_total.py", line 12, in <module>
    from virus_total_apis import PublicApi as VirusTotalPublicApi
ModuleNotFoundError: No module named 'virus_total_apis'
07/09/2019 23:10:23> [ERROR][yapsy][loadPlugins()] Unable to import plugin: /home/ggg/Downloads/Obfuscapk-master/src/obfuscapk/obfuscators/asset_encryption
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/yapsy/PluginManager.py", line 518, in loadPlugins
    candidate_module = PluginManager._importModule(plugin_module_name, candidate_filepath)
  File "/usr/local/lib/python3.7/dist-packages/yapsy/PluginManager.py", line 581, in _importModule
    candidate_module = imp.load_module(plugin_module_name,None,candidate_filepath,("py","r",imp.PKG_DIRECTORY))
  File "/usr/lib/python3.7/imp.py", line 244, in load_module
    return load_package(name, filename)
  File "/usr/lib/python3.7/imp.py", line 216, in load_package
    return _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ggg/Downloads/Obfuscapk-master/src/obfuscapk/obfuscators/asset_encryption/__init__.py", line 4, in <module>
    from .asset_encryption import AssetEncryption
  File "/home/ggg/Downloads/Obfuscapk-master/src/obfuscapk/obfuscators/asset_encryption/asset_encryption.py", line 9, in <module>
    from Crypto.Cipher import AES
ModuleNotFoundError: No module named 'Crypto'
07/09/2019 23:10:23> [ERROR][yapsy][loadPlugins()] Unable to import plugin: /home/ggg/Downloads/Obfuscapk-master/src/obfuscapk/obfuscators/lib_encryption
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/yapsy/PluginManager.py", line 518, in loadPlugins
    candidate_module = PluginManager._importModule(plugin_module_name, candidate_filepath)
  File "/usr/local/lib/python3.7/dist-packages/yapsy/PluginManager.py", line 581, in _importModule
    candidate_module = imp.load_module(plugin_module_name,None,candidate_filepath,("py","r",imp.PKG_DIRECTORY))
  File "/usr/lib/python3.7/imp.py", line 244, in load_module
    return load_package(name, filename)
  File "/usr/lib/python3.7/imp.py", line 216, in load_package
    return _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ggg/Downloads/Obfuscapk-master/src/obfuscapk/obfuscators/lib_encryption/__init__.py", line 4, in <module>
    from .lib_encryption import LibEncryption
  File "/home/ggg/Downloads/Obfuscapk-master/src/obfuscapk/obfuscators/lib_encryption/lib_encryption.py", line 9, in <module>
    from Crypto.Cipher import AES
ModuleNotFoundError: No module named 'Crypto'
07/09/2019 23:10:23> [ERROR][yapsy][loadPlugins()] Unable to import plugin: /home/ggg/Downloads/Obfuscapk-master/src/obfuscapk/obfuscators/const_string_encryption
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/yapsy/PluginManager.py", line 518, in loadPlugins
    candidate_module = PluginManager._importModule(plugin_module_name, candidate_filepath)
  File "/usr/local/lib/python3.7/dist-packages/yapsy/PluginManager.py", line 581, in _importModule
    candidate_module = imp.load_module(plugin_module_name,None,candidate_filepath,("py","r",imp.PKG_DIRECTORY))
  File "/usr/lib/python3.7/imp.py", line 244, in load_module
    return load_package(name, filename)
  File "/usr/lib/python3.7/imp.py", line 216, in load_package
    return _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ggg/Downloads/Obfuscapk-master/src/obfuscapk/obfuscators/const_string_encryption/__init__.py", line 4, in <module>
    from .const_string_encryption import ConstStringEncryption
  File "/home/ggg/Downloads/Obfuscapk-master/src/obfuscapk/obfuscators/const_string_encryption/const_string_encryption.py", line 10, in <module>
    from Crypto.Cipher import AES
ModuleNotFoundError: No module named 'Crypto'
usage: python3.7 -m obfuscapk.cli [-h] -o OBFUSCATOR [-w DIR] [-d OUT_APK]
                                  [-i] [-p] [-k VT_API_KEY]
                                  <APK_FILE>

Obfuscate an application (.apk) without needing its source code.

positional arguments:
  <APK_FILE>            The path to the application (.apk) to obfuscate

optional arguments:
  -h, --help            show this help message and exit
  -o OBFUSCATOR, --obfuscator OBFUSCATOR
                        The name of the obfuscator to use. Can be specified
                        multiple times to use more obfuscators (in sequence).
                        Allowed values are: AdvancedReflection,
                        ArithmeticBranch, CallIndirection, DebugRemoval, Goto,
                        MethodOverload, Nop, Reflection, Reorder, ClassRename,
                        FieldRename, MethodRename, RandomManifest,
                        NewAlignment, NewSignature, Rebuild
  -w DIR, --working-dir DIR
                        The working directory that will contain the
                        intermediate files. By default a directory will be
                        created in the same directory as the input
                        application. If the specified directory doesn't exist,
                        it will be created
  -d OUT_APK, --destination OUT_APK
                        The path where to save the obfuscated .apk file. By
                        default the file will be saved in the working
                        directory
  -i, --ignore-libs     Ignore known third party libraries during the
                        obfuscation operations
  -p, --show-progress   Show obfuscation progress (as a progress bar)
  -k VT_API_KEY, --virus-total-key VT_API_KEY
                        When using Virus Total obfuscator, a valid API key has
                        to be provided. Can be specified multiple times to use
                        a different API key for each request (cycling through
                        the API keys)
ggg@ubuntu:~/Downloads/Obfuscapk-master/src$ `
```

**Comment by dfdfdfs** [comment]
I installed the pycrypto module

`ggg@ubuntu:~/Downloads/Obfuscapk-master$ sudo pip3 install pycrypto
[sudo] password for ggg: 
The directory '/home/ggg/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/ggg/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting pycrypto
  Downloading https://files.pythonhosted.org/packages/60/db/645aa9af249f059cc3a368b118de33889219e0362141e75d4eaf6f80f163/pycrypto-2.6.1.tar.gz (446kB)
    100% |████████████████████████████████| 450kB 452kB/s 
Installing collected packages: pycrypto
  Running setup.py install for pycrypto ... done
Successfully installed pycrypto-2.6.1
You are using pip version 8.1.1, however version 19.2.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
ggg@ubuntu:~/Downloads/Obfuscapk-master$ `

Still writes

**ModuleNotFoundError: No module named 'Crypto'**

**Comment by ClaudiuGeorgiu** [comment]
Hi, you have to install the packages listed in the [requirements file](https://github.com/ClaudiuGeorgiu/Obfuscapk/blob/master/src/requirements.txt). However, the tool was tested only on 64 bit systems, so I don't know how it will behave on 32 bit systems.

**Comment by dfdfdfs** [comment]
I installed Unbytu 16.04 64bit
after the command
Error 

sss@ubuntu:~/Downloads/Obfuscapk-master$ cd src/
sss@ubuntu:~/Downloads/Obfuscapk-master/src$ python3.7 -m obfuscapk.cli -o RandomManifest -o Rebuild -o NewSignature -o NewAlignment sss.apk
08/09/2019 09:54:55> [ERROR][obfuscapk.tool.Apktool][decode()] Error during decode command:  09:54:43 up 10 min,  1 user,  load average: 4.03, 2.88, 1.56
USER     TTY      FROM             LOGIN@   IDLE   JCPU   PCPU WHAT
sss      tty7     :0               09:45   10:04   1:43   0.61s /sbin/upstart --user
I: Using Apktool 2.0.2-dirty on sss.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
Exception in thread "main" java.lang.NullPointerException
	at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:1792)
	at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:1769)
	at org.apache.commons.io.IOUtils.copy(IOUtils.java:1744)
	at brut.androlib.res.AndrolibResources.getFrameworkApk(AndrolibResources.java:570)
	at brut.androlib.res.AndrolibResources.loadFrameworkPkg(AndrolibResources.java:112)
	at brut.androlib.res.data.ResTable.getPackage(ResTable.java:82)
	at brut.androlib.res.data.ResTable.getResSpec(ResTable.java:65)
	at brut.androlib.res.data.ResTable.getResSpec(ResTable.java:61)
	at brut.androlib.res.decoder.ResAttrDecoder.decode(ResAttrDecoder.java:39)
	at brut.androlib.res.decoder.AXmlResourceParser.getAttributeValue(AXmlResourceParser.java:369)
	at org.xmlpull.v1.wrapper.classic.XmlPullParserDelegate.getAttributeValue(XmlPullParserDelegate.java:69)
	at brut.androlib.res.decoder.XmlPullStreamDecoder$1.parseManifest(XmlPullStreamDecoder.java:97)
	at brut.androlib.res.decoder.XmlPullStreamDecoder$1.event(XmlPullStreamDecoder.java:65)
	at brut.androlib.res.decoder.XmlPullStreamDecoder.decode(XmlPullStreamDecoder.java:141)
	at brut.androlib.res.decoder.XmlPullStreamDecoder.decodeManifest(XmlPullStreamDecoder.java:153)
	at brut.androlib.res.decoder.ResFileDecoder.decodeManifest(ResFileDecoder.java:140)
	at brut.androlib.res.AndrolibResources.decodeManifestWithResources(AndrolibResources.java:199)
	at brut.androlib.Androlib.decodeManifestWithResources(Androlib.java:140)
	at brut.androlib.ApkDecoder.decode(ApkDecoder.java:100)
	at brut.apktool.Main.cmdDecode(Main.java:165)
	at brut.apktool.Main.main(Main.java:81)

08/09/2019 09:54:55> [ERROR][obfuscapk.obfuscation][decode_apk()] Error during apk decoding: Command '['apktool', 'd', '--force', 'sss.apk', '-o', 'obfuscation_working_dir/sss']' returned non-zero exit status 1.
08/09/2019 09:54:55> [ERROR][yapsy_loaded_plugin_RandomManifest_1.random_manifest.RandomManifest][obfuscate()] Error during execution of "RandomManifest" obfuscator: Command '['apktool', 'd', '--force', 'sss.apk', '-o', 'obfuscation_working_dir/sss']' returned non-zero exit status 1.
08/09/2019 09:54:55> [CRITICAL][obfuscapk.main][perform_obfuscation()] Error during obfuscation: Command '['apktool', 'd', '--force', 'sss.apk', '-o', 'obfuscation_working_dir/sss']' returned non-zero exit status 1.
Traceback (most recent call last):
  File "/home/sss/Downloads/Obfuscapk-master/src/obfuscapk/main.py", line 88, in perform_obfuscation
    (obfuscator_name_to_function[obfuscator_name])(obfuscation)
  File "/home/sss/Downloads/Obfuscapk-master/src/obfuscapk/obfuscators/random_manifest/random_manifest.py", line 108, in obfuscate
    manifest_tree = Xml.parse(obfuscation_info.get_manifest_file(), parser=xml_parser)
  File "/home/sss/Downloads/Obfuscapk-master/src/obfuscapk/obfuscation.py", line 439, in get_manifest_file
    self.decode_apk()
  File "/home/sss/Downloads/Obfuscapk-master/src/obfuscapk/obfuscation.py", line 276, in decode_apk
    apktool.decode(self.apk_path, self._decoded_apk_path, force=True)
  File "/home/sss/Downloads/Obfuscapk-master/src/obfuscapk/tool.py", line 61, in decode
    output = subprocess.check_output(decode_cmd, stderr=subprocess.STDOUT).strip()
  File "/usr/lib/python3.7/subprocess.py", line 395, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.7/subprocess.py", line 487, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['apktool', 'd', '--force', 'sss.apk', '-o', 'obfuscation_working_dir/sss']' returned non-zero exit status 1.
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/sss/Downloads/Obfuscapk-master/src/obfuscapk/cli.py", line 81, in <module>
    arguments.interactive, arguments.ignore_libs, arguments.virus_total_key)
  File "/home/sss/Downloads/Obfuscapk-master/src/obfuscapk/main.py", line 88, in perform_obfuscation
    (obfuscator_name_to_function[obfuscator_name])(obfuscation)
  File "/home/sss/Downloads/Obfuscapk-master/src/obfuscapk/obfuscators/random_manifest/random_manifest.py", line 108, in obfuscate
    manifest_tree = Xml.parse(obfuscation_info.get_manifest_file(), parser=xml_parser)
  File "/home/sss/Downloads/Obfuscapk-master/src/obfuscapk/obfuscation.py", line 439, in get_manifest_file
    self.decode_apk()
  File "/home/sss/Downloads/Obfuscapk-master/src/obfuscapk/obfuscation.py", line 276, in decode_apk
    apktool.decode(self.apk_path, self._decoded_apk_path, force=True)
  File "/home/sss/Downloads/Obfuscapk-master/src/obfuscapk/tool.py", line 61, in decode
    output = subprocess.check_output(decode_cmd, stderr=subprocess.STDOUT).strip()
  File "/usr/lib/python3.7/subprocess.py", line 395, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.7/subprocess.py", line 487, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['apktool', 'd', '--force', 'sss.apk', '-o', 'obfuscation_working_dir/sss']' returned non-zero exit status 1.
sss@ubuntu:~/Downloads/Obfuscapk-master/src$

**Comment by dfdfdfs** [comment]
It worked ))))) Unbynty 16.04 32 bit

APK does not start

Command **python3.7 -m obfuscapk.cli -o ConstStringEncryption -o Nop -o Goto -o RandomManifest -o Rebuild -o NewSignature -o NewAlignment sss.apk**

Obfuscate apk https://mega.nz/#!FKYX3ShS!vYsSkYjqiiYXN-DYLRYsgL9UlKib7PvXc6TMGJ-Cl20

Original https://trashbox.ru/files30/220305/sms-edit-v1.4.0.apk/

**Comment by packmad** [comment]
Try to reduce the Obfuscators, until you figure out which one is not working.
Then, disassemble the app and open another issue with a *detailed* explanation of the problem

**Comment by vadivellan** [comment]
python3 -m obfuscapk.cli  -p -o AdvancedReflection -o AssetEncryption -o RandomManifest -o Rebuild -o NewSignature -o NewAlignment -w ~/Desktop/working-dir/  -d ~/Desktop/out.apk --keystore-file ~/Desktop/****.keystore --keystore-password ***** --key-alias ****** --key-password ******  ~/Desktop/input.apk

NewSignature need keystore Data 

Nop not working fine
