### ISSUE TITLE
Use AAPT2 in apktool

### ISSUE THREAD

**Issue by alvr** [ClaudiuGeorgiu/Obfuscapk#23]
Hello, I'm trying to obfuscate an APK but I got the following error:

```
30/04/2020 16:38:03> [ERROR][obfuscapk.tool.Apktool][build()] Error during build command: I: Using Apktool 2.4.1
I: Smaling smali folder into classes.dex...
I: Building resources...
W: invalid resource directory name: /Users/alvaro.salcedo.local/Desktop/input/res navigation
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/var/folders/5g/hjj3jgm50237mbgxn41lypbr0000gp/T/brut_util_Jar_7411735407958661890.tmp, p, --forced-package-id, 127, --min-sdk-version, 21, --target-sdk-version, 29, --version-code, 1, --version-name, 1.0, --no-version-vectors, -F, /var/folders/5g/hjj3jgm50237mbgxn41lypbr0000gp/T/APKTOOL1299611481270535293.tmp, -e, /var/folders/5g/hjj3jgm50237mbgxn41lypbr0000gp/T/APKTOOL3454279392600081360.tmp, -0, arsc, -I, /Users/alvaro.salcedo.local/Library/apktool/framework/1.apk, -S, /Users/alvaro.salcedo.local/Desktop/input/res, -M, /Users/alvaro.salcedo.local/Desktop/input/AndroidManifest.xml]

30/04/2020 16:48:03> [ERROR][obfuscapk.obfuscation][build_obfuscated_apk()] Error during apk building: Command '['/usr/local/bin/apktool', 'b', '--force-all', '/Users/alvaro.salcedo.local/Desktop/input', '-o', '/Users/alvaro.salcedo.local/Desktop/gd.apk']' returned non-zero exit status 1.
30/04/2020 16:48:03> [ERROR][yapsy_loaded_plugin_Rebuild_1.rebuild.Rebuild][obfuscate()] Error during execution of "Rebuild" obfuscator: Command '['/usr/local/bin/apktool', 'b', '--force-all', '/Users/alvaro.salcedo.local/Desktop/input', '-o', '/Users/alvaro.salcedo.local/Desktop/gd.apk']' returned non-zero exit status 1.
30/04/2020 16:48:03> [CRITICAL][obfuscapk.main][perform_obfuscation()] Error during obfuscation: Command '['/usr/local/bin/apktool', 'b', '--force-all', '/Users/alvaro.salcedo.local/Desktop/input', '-o', '/Users/alvaro.salcedo.local/Desktop/gd.apk']' returned non-zero exit status 1.
Traceback (most recent call last):
  File "/Users/alvaro.salcedo.local/Desktop/Obfuscapk/src/obfuscapk/main.py", line 88, in perform_obfuscation
    (obfuscator_name_to_function[obfuscator_name])(obfuscation)
  File "/Users/alvaro.salcedo.local/Desktop/Obfuscapk/src/obfuscapk/obfuscators/rebuild/rebuild.py", line 20, in obfuscate
    obfuscation_info.build_obfuscated_apk()
  File "/Users/alvaro.salcedo.local/Desktop/Obfuscapk/src/obfuscapk/obfuscation.py", line 396, in build_obfuscated_apk
    apktool.build(self._decoded_apk_path, self.obfuscated_apk_path)
  File "/Users/alvaro.salcedo.local/Desktop/Obfuscapk/src/obfuscapk/tool.py", line 106, in build
    output = subprocess.check_output(build_cmd, stderr=subprocess.STDOUT, input=b"\n").strip()
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 411, in check_output
    **kwargs).stdout
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/usr/local/bin/apktool', 'b', '--force-all', '/Users/alvaro.salcedo.local/Desktop/input', '-o', '/Users/alvaro.salcedo.local/Desktop/gd.apk']' returned non-zero exit status 1.
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/alvaro.salcedo.local/Desktop/Obfuscapk/src/obfuscapk/cli.py", line 81, in <module>
    arguments.interactive, arguments.ignore_libs, arguments.virus_total_key)
  File "/Users/alvaro.salcedo.local/Desktop/Obfuscapk/src/obfuscapk/main.py", line 88, in perform_obfuscation
    (obfuscator_name_to_function[obfuscator_name])(obfuscation)
  File "/Users/alvaro.salcedo.local/Desktop/Obfuscapk/src/obfuscapk/obfuscators/rebuild/rebuild.py", line 20, in obfuscate
    obfuscation_info.build_obfuscated_apk()
  File "/Users/alvaro.salcedo.local/Desktop/Obfuscapk/src/obfuscapk/obfuscation.py", line 396, in build_obfuscated_apk
    apktool.build(self._decoded_apk_path, self.obfuscated_apk_path)
  File "/Users/alvaro.salcedo.local/Desktop/Obfuscapk/src/obfuscapk/tool.py", line 106, in build
    output = subprocess.check_output(build_cmd, stderr=subprocess.STDOUT, input=b"\n").strip()
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 411, in check_output
    **kwargs).stdout
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/usr/local/bin/apktool', 'b', '--force-all', '/Users/alvaro.salcedo.local/Desktop/input', '-o', '/Users/alvaro.salcedo.local/Desktop/gd.apk']' returned non-zero exit status 1.
```

The problem is that I'm using the navigation component and is only compatible using `--use-aapt2` in apktool. (https://github.com/iBotPeaches/Apktool/issues/1978#issuecomment-452894225)

The command I used is `python3.7 -m obfuscapk.cli -i -p -w ~/Desktop -d ~/Desktop/gd.apk -o Rebuild -o NewSignature -o NewAlignment ~/Desktop/input.apk`

Thanks.

**Comment by ClaudiuGeorgiu** [comment]
Hi, to add more flags to `apktool` you can modify this part of the code (add the flag in the first line):
https://github.com/ClaudiuGeorgiu/Obfuscapk/blob/97cb05e19fa6b5635f96083b48639de157115217/src/obfuscapk/tool.py#L97-L107

**Comment by alvr** [comment]
Thanks, it worked!
