### ISSUE TITLE
any solution to this issue during rebuild

### ISSUE THREAD

**Issue by 9173H4vvK** [ClaudiuGeorgiu/Obfuscapk#85]
Running obfuscators (Rebuild):  62%|██████▉    |[00:11<00:07,  2.36s/obfuscator]
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/kali/Downloads/Obfuscapk/src/obfuscapk/cli.py", line 188, in <module>
    main()
  File "/home/kali/Downloads/Obfuscapk/src/obfuscapk/cli.py", line 170, in main
    perform_obfuscation(
  File "/home/kali/Downloads/Obfuscapk/src/obfuscapk/main.py", line 151, in perform_obfuscation
    (obfuscator_name_to_function[obfuscator_name])(obfuscation)
  File "/home/kali/Downloads/Obfuscapk/src/obfuscapk/obfuscators/rebuild/rebuild.py", line 20, in obfuscate
    obfuscation_info.build_obfuscated_apk()
  File "/home/kali/Downloads/Obfuscapk/src/obfuscapk/obfuscation.py", line 506, in build_obfuscated_apk
    apktool.build(
  File "/home/kali/Downloads/Obfuscapk/src/obfuscapk/tool.py", line 166, in build
    output = subprocess.check_output(
  File "/usr/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/usr/bin/apktool', '--frame-path', '/tmp', 'b', '--force-all', '/home/kali/Desktop/working-dir/edone', '-o', '/home/kali/Desktop/e2.apk']' returned non-zero exit status 1.

**Comment by ClaudiuGeorgiu** [comment]
Please follow the bug report issue template and provide all the needed information.
