### ISSUE TITLE
Error while obfuscating apk

### ISSUE THREAD

**Issue by ArchanaNair** [ClaudiuGeorgiu/Obfuscapk#86]
Hi,
I am facing the below error while trying to Obfuscate apk. Please help in resolving the issue.

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/......./Obfuscapk/src/obfuscapk/cli.py", line 188, in <module>
    main()
  File "/......./Obfuscapk/src/obfuscapk/cli.py", line 139, in main
    check_external_tool_dependencies()
  File "/....../Obfuscapk/src/obfuscapk/main.py", line 41, in check_external_tool_dependencies
    ApkSigner()
  File "/....../Obfuscapk/src/obfuscapk/tool.py", line 284, in __init__
    'Something is wrong with executable "{0}"'.format(self.apksigner_path)
RuntimeError: Something is wrong with executable "apksigner"

Comment
python3.7 -m obfuscapk.cli -o ConstStringEncryption -o CallIndirection -o Goto -o Rebuild -o NewSignature -o NewAlignment Desktop/apk/release.apk
apktool version: 2.5.0

**Comment by ClaudiuGeorgiu** [comment]
Hi, the error message should be clear enough: is `apksigner` installed properly and available from command line? See also [troubleshooting](https://github.com/ClaudiuGeorgiu/Obfuscapk/blob/master/docs/TROUBLESHOOTING.md#install-the-additional-tools-correctly).
